### PR TITLE
Optional commands arguments

### LINKED ISSUE #27: Optional commands arguments are not working for Console Commands
Module : `framework/commandhandler`

When running the command from the console, defaults value from Optional Arguments are not passed in the Command Callback. Instead the parser of the argument is executed. However, this is working when running the command from chat.

Consider this example :
image
image

### PR DESCRIPTION
**Pull request by MoskalykA**
Resolves #27

### CODE REVIEW

File: lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua [hunk 1]
```diff
@@ -22,6 +22,13 @@ function Advisor.CommandHandler.RunCommand(sender, raw, cmd, args)
     ctx:SetRawMessage(raw)
     ctx:SetParsedArguments(parsedArgs)
 
+    -- Checks if the arguments are not empty
```
Comment (Erlite) [inline lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua:25]: Not the correct way to fix this, it'd be better to check if the msgArg is valid and not empty at line 52

**Review by Erlite — CHANGES_REQUESTED** [review]

File: lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua (hunk 1 above)
Comment (Erlite) [reply lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua:25]: And by is valid, I mean not nil.

File: lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua [hunk 2]
```diff
@@ -42,7 +42,7 @@ function Advisor.CommandHandler.RunCommand(sender, raw, cmd, args)
             return ""
         end
 
-        if msgArg then
+        if msgArg and not #msgArg == 0 then
```
Comment (Erlite) [inline lua/advisor-modules/framework/commandhandler/sv_commandhandler.lua:45]: You can just simplify this to `#msgArg > 0`

**Review by Erlite — CHANGES_REQUESTED** [review]
